// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idpgixqgdtoicclttzmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcGdpeHFnZHRvaWNjbHR0em1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTc4NTgsImV4cCI6MjA2NDY5Mzg1OH0.Zc03BrXmLwOzXZJvBJJAm282dOp_45aAoutuUruffuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);